# Generated by Django 4.1.5 on 2023-02-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_metric', '0002_granularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric_settings',
            name='login',
        ),
        migrations.RemoveField(
            model_name='metric_settings',
            name='password',
        ),
    ]
